package com.example.myFirstJavaService.controller;

import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class healthController {
    
    @GetMapping("/ping")
    public String ping() {
        return "pong";
    }

    @GetMapping("/")
    public String index() {
        return """
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8">
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <title>Infrastructure Report - Jose</title>
                <style>
                    body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 40px auto; padding: 20px; background-color: #f4f4f9; }
                    .card { background: white; padding: 25px; border-radius: 8px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); margin-bottom: 20px; border-left: 5px solid #ff6600; }
                    h1 { color: #1a1a1a; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
                    h2 { color: #ff6600; margin-top: 0; }
                    code { background: #eee; padding: 2px 5px; border-radius: 4px; font-family: 'Courier New', Courier, monospace; }
                    .status { display: inline-block; padding: 5px 12px; border-radius: 20px; background: #28a745; color: white; font-size: 0.8em; font-weight: bold; }
                </style>
            </head>
            <body>
                <h1>Project: myFirstJavaService</h1>
                <p><strong>Status:</strong> <span class="status">LIVE IN MEXICO VM</span></p>

                <div class="card">
                    <h2>1. Virtual Machine Provisioning</h2>
                    <p>Successfully provisioned a Linux VM for high-performance Java execution. Configured <b>SSH Key pairs</b> for secure, passwordless deployment from local development to cloud production.</p>
                </div>

                <div class="card">
                    <h2>2. Containerized Database (Docker)</h2>
                    <p>Deployed <b>MongoDB</b> inside a Docker container. Leveraged Docker Volumes for data persistence and mapped internal ports to <code>27017</code>, ensuring the DB is isolated yet accessible to the Java layer.</p>
                </div>

                <div class="card">
                    <h2>3. Java 17 & Maven Architecture</h2>
                    <p>Initialized a Spring Boot application using <b>Java 17 SDK</b>. Used Maven for dependency management to integrate the MongoDB driver and REST capabilities.</p>
                </div>

                <div class="card">
                    <h2>4. Nginx Reverse Proxy</h2>
                    <p>Configured <b>Nginx</b> as a high-performance web server. It acts as a Reverse Proxy, receiving traffic on Port 80 and securely routing it to the Spring Boot internal port (8080).</p>
                </div>

                <div class="card">
                    <h2>5. Persistence & Management</h2>
                    <p>Utilized <code>nohup</code> for background process persistence. Verified connectivity via a <code>/ping</code> endpoint and verified the DB "Handshake" with an <code>{ok: 1}</code> response.</p>
                </div>

                <footer style="text-align: center; margin-top: 40px; color: #888; font-size: 0.9em;">
                    Report generated by Jose's Java Service | 2026
                </footer>
            </body>
            </html>
            """;
    }
}
